# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jenilrupareliya5150-bit/FlyRankAi-ml-Track/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
!git clone https://github.com/jenilrupareliya5150-bit/FlyRankAi-ml-Track.git

Cloning into 'FlyRankAi-ml-Track'...
remote: Enumerating objects: 154, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 154 (delta 62), reused 90 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (154/154), 1.88 MiB | 4.84 MiB/s, done.
Resolving deltas: 100% (62/62), done.

In [4]:
%cd FlyRankAi-ml-Track

/content/FlyRankAi-ml-Track

In [5]:
df=pd.read_csv("data/raw/content_refresh_anonymized.csv")

In [6]:
df.sample(5)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
27311,content_eac5bf5d6a11,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,commercial,5012.0,32224.0,...,25000+,0.17,28.9,1.89,6.48,1.52,good,page_3_5,up,23.7
28569,content_623acf258441,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,5758.0,37198.0,...,25000+,0.16,22.8,0.00,3.39,0.00,good,page_3_5,stable,-18.4
14490,content_fac1809db398,client_3fdba35f04,70.0,0.97,HIGH,3.01,keyword article,transactional,1543.0,9907.0,...,8000-15000,0.00,34.9,0.00,0.00,0.00,moderate,page_3_5,down,-54.7
29081,content_7a8a0681fd1c,client_f369cb89fc,0.0,0.00,LOW,0.00,keyword article,informational,2527.0,20467.0,...,15000-25000,0.00,1.2,33.33,100.00,0.00,low,top_3,new,NaN
8559,content_ce52d62a83f9,client_19581e27de,30.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,NaN,0.00,40.3,0.00,0.00,0.00,low,page_3_5,up,45.8

In [7]:
np.array(df.columns)

array(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent',
       'word_count', 'char_count', 'provider_used', 'model_used',
       'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d',
       'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d',
       'scroll_events_90d', 'days_with_impressions', 'days_with_sessions',
       'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d',
       'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d',
       'content_age_days', 'age_tier', 'age_tier_order',
       'days_since_last_update', 'freshness_tier', 'word_count_tier',
       'char_count_tier', 'ctr', 'avg_position', 'engagement_rate',
       'scroll_rate', 'ai_traffic_pct', 'impression_tier',
       'position_tier', 'trend_direction', 'trend_pct'], dtype=object)

## 1. My rule and its reason codes

I will use a simple rule to score content pages for a content-refresh action.

A page gets a higher score when it has signs such as declining traffic, declining clicks, weak search position, and an older last update. The rule will output a reason code explaining why the page received its score, such as `traffic_decline`, `click_decline`, `position_slipping`, or `stale_content`.

In [8]:

def score_page(row):
    score = 0
    reasons = []

    if row["clicks_last_30d"] < row["clicks_prev_30d"]:
        score += 1
        reasons.append("click_decline")

    if row["impressions_last_30d"] < row["impressions_prev_30d"]:
        score += 1
        reasons.append("traffic_decline")

    if row["avg_position"] > 10:
        score += 1
        reasons.append("position_slipping")

    if row["days_since_last_update"] > 180:
        score += 1
        reasons.append("stale_content")

    return score, "|".join(reasons)

## 2. Build the ranked queue (writes the CSV)

I apply the baseline rule to every content page and calculate a simple action score.

The score is based on the signals defined in Section 1. Higher scores mean that a page has more signals suggesting that it should be reviewed for a content refresh.

I also keep the reason codes so the ranking is explainable rather than being a black-box score.

In [24]:
# Make a copy so the original dataframe is not affected
score_df = df.copy()

# Start the score at 0
score_df["baseline_score"] = 0

# Reason codes
score_df["reason_code"] = ""

# Rule 1: High search demand
high_search = (
    score_df["search_volume"]
    >= score_df["search_volume"].quantile(0.75)
)

# Rule 2: Weak visibility/ranking
weak_visibility = (
    score_df["avg_position"]
    > score_df["avg_position"].median()
)

# Rule 3: Low engagement
low_engagement = (
    score_df["engagement_rate"]
    < score_df["engagement_rate"].median()
)

# Add points for each signal
score_df.loc[high_search, "baseline_score"] += 1
score_df.loc[weak_visibility, "baseline_score"] += 1
score_df.loc[low_engagement, "baseline_score"] += 1

# Add reason codes
score_df.loc[high_search, "reason_code"] += "HIGH_SEARCH;"
score_df.loc[weak_visibility, "reason_code"] += "WEAK_VISIBILITY;"
score_df.loc[low_engagement, "reason_code"] += "LOW_ENGAGEMENT;"

# Rank highest score first
score_df = score_df.sort_values(
    "baseline_score",
    ascending=False
)

# Create output folder
os.makedirs("work/outputs", exist_ok=True)

# Save the ranked queue
output_path = "work/outputs/baseline_action_score.csv"

score_df.to_csv(output_path, index=False)

# Show results
print("Rows scored:", len(score_df))
print("Output saved to:", output_path)

print("\nTop 10:")
print(
    score_df[
        ["content_id", "baseline_score", "reason_code"]
    ].head(10)
)

Rows scored: 30000
Output saved to: work/outputs/baseline_action_score.csv

Top 10:
                 content_id  baseline_score                   reason_code
1      content_a1fb4e703a9e               2  HIGH_SEARCH;WEAK_VISIBILITY;
29982  content_fe5d259e6bc5               2  HIGH_SEARCH;WEAK_VISIBILITY;
19058  content_792357bfece3               2  HIGH_SEARCH;WEAK_VISIBILITY;
19065  content_3f75aadd21f4               2  HIGH_SEARCH;WEAK_VISIBILITY;
19074  content_33cdd7617963               2  HIGH_SEARCH;WEAK_VISIBILITY;
19077  content_57e4f4fdb677               2  HIGH_SEARCH;WEAK_VISIBILITY;
29961  content_326a540b3a6e               2  HIGH_SEARCH;WEAK_VISIBILITY;
29963  content_7ba9b154acf6               2  HIGH_SEARCH;WEAK_VISIBILITY;
29966  content_77867ed726e1               2  HIGH_SEARCH;WEAK_VISIBILITY;
39     content_4595e8704e07               2  HIGH_SEARCH;WEAK_VISIBILITY;

In [25]:
import os

print("CSV exists:",
      os.path.exists("work/outputs/baseline_action_score.csv"))

print("\nOutput files:")
print(os.listdir("work/outputs"))

CSV exists: True

Output files:
['baseline_action_score.csv']

In [26]:
print(os.path.exists("work/outputs/baseline_action_score.csv"))
print(os.listdir("work/outputs"))

True
['baseline_action_score.csv']

In [27]:
baseline = pd.read_csv("work/outputs/baseline_action_score.csv")

print("Shape:", baseline.shape)
display(baseline[[
    "content_id",
    "baseline_score",
    "reason_code"
]].sample(10))

Shape: (30000, 46)

                 content_id  baseline_score                   reason_code
884    content_89bcf793d1e6               2  HIGH_SEARCH;WEAK_VISIBILITY;
26622  content_3ab08d258711               0                           NaN
16971  content_faac6ea8b055               1              WEAK_VISIBILITY;
14002  content_875d5a2daaba               1              WEAK_VISIBILITY;
8333   content_f4a36ebc5b62               1                  HIGH_SEARCH;
11100  content_577a45908bb7               1                  HIGH_SEARCH;
889    content_7886b1e2013b               2  HIGH_SEARCH;WEAK_VISIBILITY;
2743   content_2a9547be2537               2  HIGH_SEARCH;WEAK_VISIBILITY;
12874  content_5324c7411a7c               1              WEAK_VISIBILITY;
7513   content_1258820393a6               1              WEAK_VISIBILITY;

In [28]:
##DOWLOAD THE CSV FILE
#from google.colab import files

#files.download("work/outputs/baseline_action_score.csv")

## 3. Top-20 review

I will review the 20 highest-scoring pages from the baseline queue.

For each page, I will examine the baseline score and reason codes to understand why it was prioritized. I will also consider whether the available signals provide a convincing reason to recommend a refresh and identify factors that could make the rule produce a weak recommendation.

In [29]:
# Select the top 20 highest-scoring pages
top_20 = baseline.sort_values(
    "baseline_score",
    ascending=False
).head(20)

# Display the columns useful for manual review
review_cols = [
    "content_id",
    "baseline_score",
    "reason_code",
    "search_volume",
    "avg_position",
    "engagement_rate"
]

display(top_20[review_cols])

,content_id,baseline_score,reason_code,search_volume,avg_position,engagement_rate
18,content_2f51445dae6e,2,HIGH_SEARCH;WEAK_VISIBILITY;,30.0,26.6,0.00
19,content_d5d3c2e98937,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,28.9,0.00
20,content_e6cc2aad65ea,2,HIGH_SEARCH;WEAK_VISIBILITY;,210.0,14.4,0.00
21,content_f37fc7aaecaa,2,HIGH_SEARCH;WEAK_VISIBILITY;,1000.0,11.8,0.00
22,content_0f3bef6fb060,2,HIGH_SEARCH;WEAK_VISIBILITY;,320.0,35.6,3.70
23,content_69e92ae08f64,2,HIGH_SEARCH;WEAK_VISIBILITY;,140.0,12.3,0.00
24,content_774b7bb6f049,2,HIGH_SEARCH;WEAK_VISIBILITY;,20.0,35.4,0.00
25,content_4e40be86ece8,2,HIGH_SEARCH;WEAK_VISIBILITY;,210.0,12.4,0.00
26,content_cefdb6f4c6ae,2,HIGH_SEARCH;WEAK_VISIBILITY;,90.0,74.4,0.00
27,content_068840925e85,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,47.9,0.00
28,content_630a607a674d,2,HIGH_SEARCH;WEAK_VISIBILITY;,210.0,15.9,0.00
29,content_a0e0cffaef37,2,HIGH_SEARCH;WEAK_VISIBILITY;,4400.0,15.2,0.00
30,content_c389b4997335,2,HIGH_SEARCH;WEAK_VISIBILITY;,20.0,48.8,0.00
34,content_1f66df4583f7,2,HIGH_SEARCH;WEAK_VISIBILITY;,1000.0,13.2,0.00
35,content_180bc8b20006,2,HIGH_SEARCH;WEAK_VISIBILITY;,170.0,31.6,0.00
36,content_760614cd5ee6,2,HIGH_SEARCH;WEAK_VISIBILITY;,320.0,46.8,0.00
37,content_98283e312462,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,14.8,6.06
38,content_1e53ea7dbee8,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,30.1,0.00
39,content_b17dd18b28df,2,HIGH_SEARCH;WEAK_VISIBILITY;,20.0,27.4,0.00
40,content_af7ca34cc953,2,HIGH_SEARCH;WEAK_VISIBILITY;,50.0,33.1,0.00

## 4. Weak picks + leakage check
Some top-scoring pages may still be weak picks because the baseline uses simple threshold rules. I will review the top 20 for cases where the score looks high but the supporting signals are not strong.

The baseline uses search_volume, avg_position, and engagement_rate. These are available page-level signals, so I will check that no product flags or future-window information were used to create the score.

In [31]:
# Check the columns used by the baseline
print("Columns used for scoring:")
print([
    "search_volume",
    "avg_position",
    "engagement_rate"
])

# Check whether any product/label columns were used
possible_leak_columns = ["label", "product_flag", "product", "target", "future", "future_label"]

found_leaks = [
    col for col in possible_leak_columns
    if col in score_df.columns
]

print("\nPossible leakage columns found:")
print(found_leaks)

# Show the top 20 again for manual review
print("\nTop 20 for review:")

display(
    top_20[
        [
            "content_id",
            "baseline_score",
            "reason_code",
            "search_volume",
            "avg_position",
            "engagement_rate"
        ]
    ]
)

Columns used for scoring:
['search_volume', 'avg_position', 'engagement_rate']

Possible leakage columns found:
[]

Top 20 for review:

,content_id,baseline_score,reason_code,search_volume,avg_position,engagement_rate
18,content_2f51445dae6e,2,HIGH_SEARCH;WEAK_VISIBILITY;,30.0,26.6,0.00
19,content_d5d3c2e98937,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,28.9,0.00
20,content_e6cc2aad65ea,2,HIGH_SEARCH;WEAK_VISIBILITY;,210.0,14.4,0.00
21,content_f37fc7aaecaa,2,HIGH_SEARCH;WEAK_VISIBILITY;,1000.0,11.8,0.00
22,content_0f3bef6fb060,2,HIGH_SEARCH;WEAK_VISIBILITY;,320.0,35.6,3.70
23,content_69e92ae08f64,2,HIGH_SEARCH;WEAK_VISIBILITY;,140.0,12.3,0.00
24,content_774b7bb6f049,2,HIGH_SEARCH;WEAK_VISIBILITY;,20.0,35.4,0.00
25,content_4e40be86ece8,2,HIGH_SEARCH;WEAK_VISIBILITY;,210.0,12.4,0.00
26,content_cefdb6f4c6ae,2,HIGH_SEARCH;WEAK_VISIBILITY;,90.0,74.4,0.00
27,content_068840925e85,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,47.9,0.00
28,content_630a607a674d,2,HIGH_SEARCH;WEAK_VISIBILITY;,210.0,15.9,0.00
29,content_a0e0cffaef37,2,HIGH_SEARCH;WEAK_VISIBILITY;,4400.0,15.2,0.00
30,content_c389b4997335,2,HIGH_SEARCH;WEAK_VISIBILITY;,20.0,48.8,0.00
34,content_1f66df4583f7,2,HIGH_SEARCH;WEAK_VISIBILITY;,1000.0,13.2,0.00
35,content_180bc8b20006,2,HIGH_SEARCH;WEAK_VISIBILITY;,170.0,31.6,0.00
36,content_760614cd5ee6,2,HIGH_SEARCH;WEAK_VISIBILITY;,320.0,46.8,0.00
37,content_98283e312462,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,14.8,6.06
38,content_1e53ea7dbee8,2,HIGH_SEARCH;WEAK_VISIBILITY;,40.0,30.1,0.00
39,content_b17dd18b28df,2,HIGH_SEARCH;WEAK_VISIBILITY;,20.0,27.4,0.00
40,content_af7ca34cc953,2,HIGH_SEARCH;WEAK_VISIBILITY;,50.0,33.1,0.00

## Self-check

Before you submit, confirm each line honestly:

- [✅] Every section above is filled — markdown thinking AND the code that backs it
- [✅] The notebook runs top to bottom with no errors (Runtime → Run all)
- [✅] No client names, URLs, or private queries anywhere
- [✅] My claims use careful words: observed, measured, directional, decision-support
- [✅] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.